### ISSUE TITLE
.NET Core 2.0 port

### ISSUE THREAD

**Issue by shanselman** [shanselman/dasblog#33]
- [x] Upgraded all project to 4.6.X (preliminary testing looks good)
- [x] Created a new ASP.NET Web Core 2 project (thanks for the connect with Mr. Hunter btw)
Using .NET Standard 2.0 integrated Web Core with DasBlog (core/runtime/service), just needed a few small changes
- [x] Integrating ViewLocationExpanders to support "Themes"
- [x] AddIISUrlRewrite middleware to support 301 redirects for the more static ".aspx" (archives.aspx, monthview.aspx, etc.)
- [x] Integrate existing dasBlog config (meta, security, site, etc)
- [x] Integrate with old original dasBlog layer via repository pattern
- [x] Support for RSS/RSS by category
- [x] Support for Sitemap
- [x] Support for Paging on blog home page page/1, page/2, etc.
 
There are still many problems to consider but .NET standard 2 puts them in reach, they include:
- [ ] Routing that supports new URLs
- [ ] Do not ruin old URLs and support new post URLs
- [ ] How do we deal with satellite resx files?
- [ ] Two stage build? Make net45 stuff, pack as nuget, then consume?
- [ ] Can we build on Linux?
- [ ] How to handle page meta data?
- [ ] Publishing/Editing posts through a UI
- [ ] Integrating XML/RPC with ASP.NET Core
- [ ] Site security integration (validation)
- [ ] Login and administrative pages
- [ ] Do sites need to ping servers when we have new posts
- [ ] Comments support (comment filters)
- [ ] Email alerts? When we have a new post or comment added
- [ ] Our concept of time is custom and obsolete. Try integrating NodaTime
- [ ] Logging (errors, information)
- [ ] Support links to "Previous/Next" pages

**Comment by poppastring** [comment]
Will be doing this work [over here](https://github.com/poppastring/dasblog-core)
